apiVersion: v1
kind: Pod
metadata:
  name: application-pod
  labels:
    app: application
spec:
  containers:
  - name: application-container
    image: 534731196878.dkr.ecr.us-east-1.amazonaws.com/application
    ports:
    - containerPort: 8080