apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application-replicaset
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: myapp-container
        image: 534731196878.dkr.ecr.us-east-1.amazonaws.com/application
        ports:
        - containerPort: 8080