apiVersion: v1
kind: Service
metadata:
  name: application-service
  labels:
  app: employees
spec:
  selector:
   app: employees
  type: NodePort 
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 3000
  type: LoadBalancer