apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    component: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: 570629616813.dkr.ecr.us-east-1.amazonaws.com/database-image-clo835-kubernetes-assignment:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pw
          ports:
            - containerPort: 3306
      imagePullSecrets:
          - name: regcred
