apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: 534731196878.dkr.ecr.us-east-1.amazonaws.com/database:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      ports:
        - containerPort: 3306
  imagePullSecrets:
          - name: regcred